spring.application.name=documaster

# ===============================
#   SERVER CONFIGURATION
# ===============================
server.port=8080

# ===============================
#   DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/documaster
spring.datasource.username=documasteruser
spring.datasource.password=documasterpass

# ===============================
#   JPA CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show.sql=true

# ===============================
#   FILE STORAGE
# ===============================
app.storage.location=./uploads
app.file.cleanup.cron=0 0 0  * * ?